name: Build AppImage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libx11-dev libxcomposite-dev \
          libxdamage-dev libxinerama-dev libxft-dev libjpeg-dev libgif-dev \
          libpng-dev zlib1g-dev appstream

    - name: Download appimagetool
      run: |
        wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
        chmod +x appimagetool

    - name: Build AppImage
      run: |
        ./appimagetool skippy-xd.AppDir Skippy-XD.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Skippy-XD.AppImage
        path: Skippy-XD.AppImage

    - name: Upload to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: Skippy-XD.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
